### ISSUE TITLE
Question regarding re-using SWAPI data for GraphQL

### ISSUE THREAD

**Issue by marceloverdijk** [phalt/swapi#106]
Hi @phalt,

I'm creating a GraphQL version (https://github.com/marceloverdijk/swapi-graphql) of the SWAPI for demo purposes.

1. Is it ok to re-use the data of SWAPI? If needed I can put a link to https://swapi.co/ or whatever you  think is appropriate.

1. According to #53 the fixture data in the repo is behind the hosted api. Would it be possible to update the fixtures data or provide an old-fashioned database dump? The latter one would even be easier for me as I'm not using Django (and I would need to rewrite the Django fixtures to plain SQL inserts anyway).

Feedback would be appreciated.

**Comment by phalt** [comment]
@marceloverdijk absolutely fine to scrape it. It's what it is there for :)

If you want to update the fixtures afterwards (I know they're a little out of date) then feel free to make a PR.

**Comment by marceloverdijk** [comment]
@phalt thx for feedback 👍

**Comment by marceloverdijk** [comment]
I somebody is interested in raw sql statements check out https://github.com/marceloverdijk/swapi-labs/tree/master/swapi-labs-data/src/main/resources
