### ISSUE TITLE
GET:people list and GET:id

### ISSUE THREAD

**Issue by cemiluzunhasan** [phalt/swapi#114]
In people, results indexes and their ids are different. For example : 
     Results[32] = Obi wan
     GET: people/32 = R2 (just an example. Not exact)

**Comment by mbaas2** [comment]
Well, they don't have to be in sync and you shouldn't assume they are - so I'd say it's good they aren't ;-)

**Comment by phalt** [comment]
Use hyperlinks! That's what REST is for!
