### ISSUE TITLE
The API is down

### ISSUE THREAD

**Issue by ne0nv0id** [phalt/swapi#144]
![Screenshot from 2020-02-12 16-27-56](https://user-images.githubusercontent.com/17284549/74379302-89878200-4db5-11ea-893d-e15895b94a50.png)

**Comment by phalt** [comment]
It looks like someone is hammering the API. I restarted it and I can access it now. I don't have time to handle mitigation of bad actors I'm afraid. Please fork and run your own instance if you need it up 100% of the time :) (service is free after all!)
