### ISSUE TITLE
Search for Resources via name

### ISSUE THREAD

**Issue by jlcarvalho** [phalt/swapi#20]
In Pokeapi, we can search for Pokémon via name:

`HTTP GET /api/v1/pokemon/mew`

It would be amazing to have this feature in SWAPI.

`HTTP GET /api/people/Yoda`

**Comment by phalt** [comment]
I think this might go well with #3, as you can just filter on a specific name (which should only return one result).

**Comment by jlcarvalho** [comment]
Nice!
