### ISSUE TITLE
Adding release date to films data

### ISSUE THREAD

**Issue by carvilsi** [phalt/swapi#22]
Hi!

First of all, thanks for this amazing API!

I am wondering if you have planed to add the release date of film into the data. 

E.g. for Episode IV - A New Hope --> 25 May 1977 (USA)

If you think is an interesting feature, maybe I can help implementing

Best regards.

**Comment by phalt** [comment]
@carvilsi Hey Carl, shouldn't be too hard to do. Would involve adding a new attribute on the Film model, making sure a migration file is created and ran on the server, and then the data added to the live database.

Feel free to make a PR and give it a shot.

**Comment by carvilsi** [comment]
Hi Phalt.

Thanks, I will try.
