### ISSUE TITLE
?format=wookiee does not work

### ISSUE THREAD

**Issue by phalt** [phalt/swapi#27]
Hi @astagi, the url formatting does not properly work.

I tried it out and I get 404 errors. Can you please write a test that mimics the tests we have for urls, but with your rendering? That should help you understand what the bug is, and then fix it.

I've rolled back to a previous version for now.

**Comment by astagi** [comment]
It doesn't work because it's "wookie" but "wookiee" should be the correct name to use, right?

**Comment by astagi** [comment]
@phalt I've update my branch https://github.com/astagi/swapi/tree/feature/wookie

**Comment by phalt** [comment]
Please rebase with the master branch. "wookiee" is the correct spelling.

**Comment by astagi** [comment]
Oh I haven't seen new commits on the master branch! no problem, sorry for the typo

**Comment by astagi** [comment]
Rebased https://github.com/astagi/swapi/tree/feature/wookie, do you need a new PR?
