### ISSUE TITLE
Add Photo for people

### ISSUE THREAD

**Issue by oliveiradev** [phalt/swapi#50]
Add photo url for people on people/anyId

**Comment by phalt** [comment]
@oliveiradev hey! Had this asked many times before, as it's a duplicate I'm gonna close it :) #4

**Comment by oliveiradev** [comment]
@phalt hey! ok , but this ask it will be implemented?

**Comment by phalt** [comment]
@oliveiradev Also discussed on the linked ticket - #4 

Happy to accept a pull request that adds consistent images!

**Comment by oliveiradev** [comment]
@phalt ok , thanks for your time!
