### ISSUE TITLE
CORS allow headers

### ISSUE THREAD

**Issue by focusaurus** [phalt/swapi#60]
Would you consider adding CORS headers similar to below so the API (read-only) could be accessed directly from browser code?

```
Access-Control-Allow-Origin: *
Access-Control-Allow-Headers: Cache-Control, Pragma, Origin, Authorization, Content-Type, X-Requested-With
Access-Control-Allow-Methods: GET
```

I would like to use this API while teaching some front end coding courses and would like my students to be able to just fire up a new tab in their browser and start making requests via `fetch`.

**Comment by phalt** [comment]
This should be an easy feature to implement. Happy to accept PR's making this change!

**Comment by sergeysolovev** [comment]
@focusaurus @phalt Isn't that [already implemented](https://github.com/phalt/swapi/blob/master/swapi/settings.py#L154-L158)? Some of the headers, mentioned above, are [already included](https://github.com/ottoyiu/django-cors-headers#cors_allow_headers) by default in django-cors-headers. Please, correct me if I'm wrong. 

Also fetch is working fine from dev tools console:

![screenshot 2017-06-25 00 55 56](https://user-images.githubusercontent.com/5831301/27510356-2cf1fe64-5941-11e7-9b64-0d542d86942c.png)

**Comment by focusaurus** [comment]
It looks like if the request includes an `Origin` header, then the response includes the appropriate `Access-Control-Allow-Origin: *` header. Thanks!
