### ISSUE TITLE
API return 404 for `starships/1/`

### ISSUE THREAD

**Issue by olivierobert** [phalt/swapi#97]
As tested on the site [swapi.co](https://swapi.co/), querying for `https://swapi.co/api/starships/1/` returns 404:

![swapi_-_the_star_wars_api](https://user-images.githubusercontent.com/696529/29159275-222dac4c-7dd8-11e7-88ac-afd57e33f7fa.png)

**Comment by kaustubhtalathi** [comment]
There are url's matching 1 and hence the 404. Confirm with following data: https://swapi.co/api/starships/

**Comment by olivierobert** [comment]
I understand why it returns `404` as there is simply no data for it. But it might better to clean up the IDs of all data points to have continuous IDs. When testing the API, it's likely other people like me will start at the ID `1` 😉

**Comment by phalt** [comment]
@olivierobert ID could be a purely random number, it just happens to have some order. Humans recognise patterns :)
