### ISSUE TITLE
API return 404 for `https://swapi.co/api/people/17/ `

### ISSUE THREAD

**Issue by Errec** [phalt/swapi#99]
Getting 404 for people 17 https://swapi.co/api/people/17/

**Comment by kaustubhtalathi** [comment]
There is no one with 17 and hence the 404. Checkout https://swapi.co/api/people/ to confirm.

**Comment by Gardner-Jeremy** [comment]
In the person.json file, the pk number for each person increments. When creating the data, it appears 17 was simply skipped over. It would be nice to get this resolved and renumber the people so that 17 exists.

**Comment by anthonybrown** [comment]
yep, there is no data in `https://swapi.co/people/17`
